<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class delegate_registration extends Model
{
    use HasFactory;

    protected $table = 'delegate_table';

    protected $fillable = [
        'exhibitor_id',
        'sector',
        'org_type',
        'delegates_count',
        'nationality',
        'student',
        'studentid', 
        'organization_name',
        'address1',
        'address2',
        'city',
        'state',
        'country',
        'zip_code',
        'gst_details',
        'gst_number',
        'gst_invoice_add',
        'pan_number',

        'del1_name',
        'del1_email',
        'del1_designation',
        'del1_contact',
        'del1_type',
        'del2_name',
        'del2_email',
        'del2_designation',
        'del2_contact',
        'del2_type',
        'del3_name',
        'del3_email',
        'del3_designation',
        'del3_contact',
        'del3_type',
        'del4_name',
        'del4_email',
        'del4_designation',
        'del4_contact',
        'del4_type',
        'del5_name',
        'del5_email',
        'del5_designation',
        'del5_contact',
        'del5_type',
        'del6_name',
        'del6_email',
        'del6_designation',
        'del6_contact',
        'del6_type',
        'reg_id',
        'user_type',
        'reg_date',
        'tin_no',
        'currency',
        'amt_ext',
        'paymode',
        'pay_status',
        'payment_date',
        'pin_no',
        'selection_amount',
        'promo_code',
        'discount',
        'tax_amount',
        'processing_charge',
        'total_amount',
        'total_amt_received',
        'pg_errorText',
        'pg_paymentId',
        'pg_trackId',
        'pg_result',
        'pg_tranid',
        'pg_auth',
        'pg_avr',
        'pg_ref',
        'pg_amt',
        'gst_state',
        'group_type',
        'del_govt1',
        'del_govno1',
        'del_govt2',
        'del_govno2',
        'del_govt3',
        'del_govno3',
        'del_govt4',
        'del_govno4',
        'del_govt5',
        'del_govno5',
        'del_govt6',
        'del_govno6',
        'user_type',
        'assoc_name',
        'event_name',
        'event_year',
        'token',
    ];
    
}
